name: roman-data-workshop-env

dependencies:
  - jupyter
  - notebook >= 6.0
  - matplotlib >= 3.2
  - numpy >= 1.20
  - packaging
  - pip
  - python >= 3.9
  - pyyaml
  - pip:
      - romancal >= 0.11
      - jwst >= 1.10.2
