name: roman-data-workshop-env

dependencies:
  - jupyter
  - notebook >= 6.0
  - matplotlib >= 3.2
  - numpy >= 1.20
  - packaging
  - pip
  - python >= 3.9
  - pyyaml
  - pip:
      - asdf
      - asdf-astropy >= 0.4.0
      - asdf-standard
      - astropy >= 5.3
      - gwcs >= 0.18.3
      - stpipe == 0.5.0
      - romancal >= 0.11
      - jwst >= 1.10.2
