name: roman-data-workshop-env

dependencies:
  - jupyter
  - notebook >= 6.0
  - matplotlib >= 3.2
  - numpy >= 1.16
  - packaging
  - pip
  - python >= 3.9
  - pyyaml
  - pip:
      - asdf
      - asdf-astropy
      - asdf-standard
      - astropy >= 4.2
      - gwcs >= 0.16
      - romancal
